simpler code
HelgeGehring/femwell pull request #12
Opened 2022-11-30 02:58 UTC by joamatab

2022-12-28 23:20 UTC, HelgeGehring requested changes
Many of the suggested code changes improve the code quality, thanks!

Some of them can be improved a bit more and some changes rather lower the code quality, I've made some suggestions :)

@simbilod could you have a look on the changes regarding the meshing?

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/mesh.py
> +        )
I think this makes the code way harder to understand, what do you think?
I'd suggest staying with the previous form (and removing the not needed space)
```suggestion
        for index, shapely_point in enumerate(self.shapely_points):
            if xy_point.equals_exact(shapely_point, self.atol):
                return index
        return None
```

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/mesh.py
> +                return (index, True) if first_xy_line.equals(first_xy) else (index, False)
```suggestion
                return (index, first_xy_line.equals(first_xy))
```
seems even cleaner @simbilod ?

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/mesh.py
> +            refinement_fields.extend((n+1, n+3))
I don't see the point removing the command, @simbilod ?
```suggestion
           # Save and increment
            refinement_fields.extend((n+1, n+3))
```

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/mesh/mesh.py
> +        ]
```suggestion
        rings = [
            LineString(list(object.exterior.coords))
            for object in listpoly if not (object.type in ["Point", "LineString"] or object.is_empty)
        ]
```

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/mesh/mesh.py
> +        shapes_tiled_list = list(polygonize(union))
Maybe directly inline this in line 74? Or keep the variable for better readability? Is the conversion to a list necessary at all? @simbilod

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/mesh/mesh.py
> +                    # gmsh.model.occ.synchronize()
This indentation seems wrong to me
```suggestion
            # Fuse edges (bandaid)
            # gmsh.model.occ.synchronize()
            # gmsh.model.occ.removeAllDuplicates()
            # gmsh.model.occ.synchronize()
```

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/mesh/meshtracker.py
> +        )
```suggestion
    def get_point_index(self, xy_point):
        for index, shapely_point in enumerate(self.shapely_points):
            if xy_point.equals_exact(shapely_point, self.atol) :
                return index
        return None
```
As before, this seems to lower the readability

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/mesh/meshtracker.py
> +                return (index, True) if first_xy_line.equals(first_xy) else (index, False)
```suggestion
                return (index, first_xy_line.equals(first_xy))
```

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/mesh/meshtracker.py
> +        for _ in shapely_xy_polygon.geoms if hasattr(shapely_xy_polygon, 'geoms') else [shapely_xy_polygon]:
@simbilod is it intentional that `polygon` is not used at all?

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/mesh/slice.py
> +        vertices.extend(iter(MultiPoint(polygon_hole.coords).geoms))
is `iter` necessary here?

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/mesh/slice.py
> +    vertices.extend(iter(MultiPoint(polygon.exterior.coords).geoms))
is `iter` necessary here?

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/tests/test_mesh.py
> -    assert True
@simbilod these asserts are important to make the test run, right?

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/waveguide.py
> +
```suggestion
        mesh = mesh_waveguide(wsim=2, hclad=.7, hbox=.5, wcore=0.5, hcore=0.22, filename=f'{tmpdirname}/mesh.msh')
```
I'd guess breaking the parameters into lines would lower the readability, as the file focusses on implementing the simulation and the parameters for the example are not in focus here

2022-12-28 23:20 UTC, HelgeGehring commented on docs/source/photonics/examples/vary_width.py
> +
```suggestion
            mesh_from_OrderedDict(polygons, resolutions, filename=f'{tmpdirname}/mesh.msh', default_resolution_max=.6)
```
The usage of f-strings is nice! I don't see the point in adding the line breaks here.

2022-12-28 23:20 UTC, HelgeGehring commented on docs/source/photonics/examples/waveguide_modes.py
> +
```suggestion
    mesh_from_OrderedDict(polygons, resolutions, filename=f'{tmpdirname}/mesh.msh', default_resolution_max=10)

```
The usage of f-strings is nice! I don't see the point in adding the line breaks here.

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/culomb.py
> +
```suggestion
        mesh_from_OrderedDict(polygons, resolutions, filename=f'{tmpdirname}/mesh.msh', default_resolution_max=5)
```
The usage of f-strings is nice! I don't see the point in adding the line breaks here.

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/eme.py
> +    meshnames = [f"mesh_x_{x1}.msh"]
I'd guess this is already prepared for being put in a loop? @simbilod Therefore, I'd suggest not changing this?
```suggestion
    meshnames.append(f"mesh_x_{x1}.msh")
```

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/eme.py
>      lengths = []
```suggestion
    lengths = []
    meshnames = []
```
I'd guess this is already prepared for being put in a loop? @simbilod Therefore, I'd suggest not changing this?

2022-12-28 23:20 UTC, HelgeGehring commented on femwell/examples/overlap_integrals.py
> +
```suggestion
mesh = mesh_waveguide(wsim=2, hclad=.7, hbox=.5, wcore=width, hcore=0.22, filename=f'{tmpdirname}/mesh.msh')
```
I'd guess breaking the parameters into lines would lower the readability, as the file focuses on implementing the simulation and the parameters for the example are not in focus here. The usage of f-strings is nice!

2022-12-30 15:37 UTC, simbilod commented
On the gdsfactory version of this I just accept all the reformatting, since it usually doesn't break the logic, it's less effort, and readability remains OK

In the end I'm also still not fully 100% happy with this meshing code, because complete 3D functionality will require more constructive geometry at the gmsh level. This will simplify the 2D version too.

2022-12-30 21:38 UTC, HelgeGehring commented
@simbilod 
Okay, then I'll do the same :)
I'm only worried about 
```
        for _ in shapely_xy_polygon.geoms if hasattr(shapely_xy_polygon, 'geoms') else [shapely_xy_polygon]:
```
Is it intentional, that the variable it loops over is not used at all?

2023-01-01 00:29 UTC, HelgeGehring commented on femwell/mesh/meshtracker.py
> +        for _ in shapely_xy_polygon.geoms if hasattr(shapely_xy_polygon, 'geoms') else [shapely_xy_polygon]:
might it be that the code within the loop should use `polygon` instead of `shapely_xy_polygon`?

2023-01-01 01:51 UTC, merged